{"nextFeatureIndex": 1, "attempts": 0, "errors": [{"elementID": 0, "error": "Traceback (most recent call last):\n  File \"/geemap/data/classification/assessment_main.py\", line 171, in assessment\n    loopThroughAoI(featureIndex)\n  File \"/geemap/data/classification/assessment_main.py\", line 109, in loopThroughAoI\n    imageData = imagery.get(filtered.geometry(), classificationStart, classificationEnd)\n  File \"/geemap/data/classification/./imagery/imagery.py\", line 13, in get\n    return harmonization.ref(aoi, startDate, endDate)\n  File \"/geemap/data/classification/./imagery/harmonization.py\", line 130, in ref\n    imageCollection = getHarmonizedCollection(aoi, startDate, endDate)\n  File \"/geemap/data/classification/./imagery/harmonization.py\", line 121, in getHarmonizedCollection\n    filtered = col.filterDate(startDate, endDate).filterBounds(aoi.geometry().bounds())\nAttributeError: 'Geometry' object has no attribute 'geometry'\n"}, {"elementID": 0, "error": "Traceback (most recent call last):\n  File \"/geemap/data/classification/assessment_main.py\", line 171, in assessment\n    loopThroughAoI(featureIndex)\n  File \"/geemap/data/classification/assessment_main.py\", line 109, in loopThroughAoI\n    imageData = imagery.get(filtered.geometry(), classificationStart, classificationEnd)\n  File \"/geemap/data/classification/./imagery/imagery.py\", line 13, in get\n    return harmonization.ref(aoi, startDate, endDate)\n  File \"/geemap/data/classification/./imagery/harmonization.py\", line 130, in ref\n    imageCollection = getHarmonizedCollection(aoi, startDate, endDate)\n  File \"/geemap/data/classification/./imagery/harmonization.py\", line 121, in getHarmonizedCollection\n    filtered = col.filterDate(startDate, endDate).filterBounds(aoi.geometry().bounds())\nAttributeError: 'Geometry' object has no attribute 'geometry'\n"}]}